import { config } from 'dotenv'
// config({ path: '../../.env' })
config()

const NODE_ENV = process.env.NODE_ENV
const MONGODB_URL =
    NODE_ENV === 'production'
        ? process.env.MONGODB_URL
        : 'mongodb://localhost:27017/deepstudy'

const JWT_REFRESH_TOKEN_SECRET = process.env.JWT_REFRESH_TOKEN_SECRET
const JWT_REFRESH_TOKEN_EXPIRY = process.env.JWT_REFRESH_TOKEN_EXPIRY
const JWT_ACCESS_TOKEN_SECRET = process.env.JWT_ACCESS_TOKEN_SECRET
const JWT_ACCESS_TOKEN_EXPIRY = process.env.JWT_ACCESS_TOKEN_EXPIRY

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
const GOOGLE_REDIRECT_URL = process.env.GOOGLE_REDIRECT_URL
const GOOGLE_AUTH_SCOPES = JSON.parse(process.env.GOOGLE_AUTH_SCOPES)

const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID
const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET
const GITHUB_REDIRECT_URL = process.env.GITHUB_REDIRECT_URL

const FRONTEND_URL = NODE_ENV === 'production' ? process.env.FRONTEND_URL : '*'
const SERVER_PORT = process.env.SERVER_PORT
const SALT_ROUNT = process.env.SALT_ROUNT

export {
    MONGODB_URL,
    JWT_REFRESH_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_EXPIRY,
    JWT_ACCESS_TOKEN_SECRET,
    JWT_ACCESS_TOKEN_EXPIRY,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URL,
    GOOGLE_AUTH_SCOPES,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GITHUB_REDIRECT_URL,
    FRONTEND_URL,
    SERVER_PORT,
    SALT_ROUNT,
    NODE_ENV,
}